version: '2.27.0'

services:

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS = "-Xms256m -Xmx2g"
      - discovery.type=single-node
      - xpack.security.enabled= false
      - xpack.security.enrollment.enabled= false
    mem_limit: 1024m

  logstash:
    image: logstash:8.13.0
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/:/var/log/apache/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    mem_limit: 1024m
volumes:
  elastic-data:
